### PR TITLE
Use maltpynt wherever possible to save/load data in mission and intermediate product formats

### PR DESCRIPTION
**Pull request by matteobachetti**
- [x] Eliminate need for most stingray_addons

Save and load intermediate products:
- [x] event lists
- [x] calibrated event lists
- [x] light curves
- [x] power density spectra/cross spectra

### CODE REVIEW

**Comment by pbalm** [comment]
Can one of the admins verify this patch?

**Comment by matteobachetti** [comment]
Thanks @ricardovb!

**Comment by matteobachetti** [comment]
@ricardovb @pbalm I added a 'ready for review' label :).

**Review by ricardovb — APPROVED** [review]

**Comment by pbalm** [comment]
There were some conflicts but they were trivial to resolve, so I've done that.

**Review by pbalm — APPROVED** [review]

**Pull request merged**
