### PR TITLE
Minor fixes in server.py

### PR DESCRIPTION
**Pull request by OrkoHunter**
@pbalm

### CODE REVIEW

**Review by OrkoHunter — COMMENTED** [review]
@pep8speaks suggest diff

**Review by OrkoHunter — COMMENTED** [review]
@pep8speaks pep8ify

**Comment by OrkoHunter** [comment]
@pbalm The bot created a [PR using autopep8](https://github.com/OrkoHunter/dave/pull/1) on my branch with not all but most fixes after the last review comment.

**Comment by pbalm** [comment]
@OrkoHunter Thanks for the fixes :-)

**Pull request merged**
