### PR TITLE
 Generalize event list loading

### PR DESCRIPTION
**Pull request by matteobachetti**
- [x] Use maltpynt's load_events_and_gtis, as it understands better different file formats.. like which GTI extension(s) to use in XMM files! (GTIs change for every detector of PN, for example)
- [x] Use TSTART as time reference (please)
- [x] Exit gracefully if PHA column not present in files
- [x] Add maltpynt installation to setup

### CODE REVIEW

**Comment by pbalm** [comment]
Can one of the admins verify this patch?

**Comment by ricardovb** [comment]
Im going to review it tomrrow. 👍🏻

**Comment by matteobachetti** [comment]
I just copied and pasted from the stingray installation :D
Can I take the liberty of installing a few more dependencies, so that we can work on the bootstrap thing? We need emcee and statsmodels

**Comment by ricardovb** [comment]
Go for it !!

**Review by ricardovb — APPROVED** [review]

**Comment by ricardovb** [comment]
Just ready to merge!

**Comment by pbalm** [comment]
@matteobachetti Is this ready to be merged for real? Since the title still has "WIP"?

**Comment by matteobachetti** [comment]
@pbalm yep

**Pull request merged**
